version: "2"

services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=PharmacyBE
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./mongo-volumn:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    depends_on:
      - node1
      - node2
      - node3
    ports:
      - "80:80"
    networks:
      - app-network

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    depends_on:
      - mongodb
    networks:
      - app-network

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node2
    depends_on:
      - mongodb
    networks:
      - app-network

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node3
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
