export enum OrderStatus {
  UNCONFIRMED = 'UNCONFIRMED',
  INITIATED = 'INITIATED',
  PROCESSED = 'PROCESSED',
  PICKED = 'PICKED',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED'
}
